version: "3.9"
networks:
    nginx_network:
      external: true
   
services:
  node:
    working_dir: /app
    build: .
    container_name: website
    volumes:
      - ./:/app
    tty: true
    restart: always  